### ISSUE TITLE
Add the doubly linked list.

### ISSUE THREAD

**Issue by abhishektripathi66** [abhishektripathi66/DSA#21]
As of now in the Repo, we don't have the doubly LinkedList, Please add that with proper explanation.

**Comment by yuvi-mittal** [comment]
I am interested , Can I work on this ?

**Comment by abhishektripathi66** [comment]
Assigned to you @yuvi-mittal

**Comment by abhishektripathi66** [comment]
Thanks @yuvi-mittal, For adding the Doubly Linked List.
