### ISSUE TITLE
Add Binary Tree

### ISSUE THREAD

**Issue by abhishektripathi66** [abhishektripathi66/DSA#22]
As of now in the repo we dont have the Documentation and the code for the Binary Tree, Please do add it.

**Comment by surendra-sk** [comment]
i'm interested can i work on it?

**Comment by surendra-sk** [comment]
can you label this as hacktoberfest

**Comment by abhishektripathi66** [comment]
> can you label this as hacktoberfest

Done added @surendra-sk

**Comment by abhishektripathi66** [comment]
Thanks for your Contribution @surendra-sk
